version: '3'
networks:
  app:

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - app
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app:delegated
    ports:
      - "3000:3000"
    environment:
      - PGHOST=0.0.0.0:5432
    depends_on:
      - db
    networks:
      - app